services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
        driver: local
        name: wordpress
        driver_opts:
            type: none
            device: ~/data/wordpress
            o: bind
  mariadb:
        driver: local
        name: mariadb
        driver_opts:
            type: none
            device: ~/data/mariadb
            o: bind


